version: '3.8'
services:
  db:
    image: postgres:15
    container_name: spendwise_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root:
      POSTGRES_DB: spendwise
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  db_data:
    name: spendwise